// Code generated by ent, DO NOT EDIT.

package fighter

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the fighter type in the database.
	Label = "fighter"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUfcFighterID holds the string denoting the ufc_fighter_id field in the database.
	FieldUfcFighterID = "ufc_fighter_id"
	// FieldMmaID holds the string denoting the mma_id field in the database.
	FieldMmaID = "mma_id"
	// FieldFirstName holds the string denoting the first_name field in the database.
	FieldFirstName = "first_name"
	// FieldLastName holds the string denoting the last_name field in the database.
	FieldLastName = "last_name"
	// FieldNickName holds the string denoting the nick_name field in the database.
	FieldNickName = "nick_name"
	// FieldFightinsiderID holds the string denoting the fightinsider_id field in the database.
	FieldFightinsiderID = "fightinsider_id"
	// FieldTapologyID holds the string denoting the tapology_id field in the database.
	FieldTapologyID = "tapology_id"
	// EdgeFights holds the string denoting the fights edge name in mutations.
	EdgeFights = "fights"
	// EdgeFighterAliases holds the string denoting the fighter_aliases edge name in mutations.
	EdgeFighterAliases = "fighter_aliases"
	// EdgeFighterResults holds the string denoting the fighter_results edge name in mutations.
	EdgeFighterResults = "fighter_results"
	// Table holds the table name of the fighter in the database.
	Table = "fighters"
	// FightsTable is the table that holds the fights relation/edge. The primary key declared below.
	FightsTable = "fighter_results"
	// FightsInverseTable is the table name for the Fight entity.
	// It exists in this package in order to avoid circular dependency with the "fight" package.
	FightsInverseTable = "fights"
	// FighterAliasesTable is the table that holds the fighter_aliases relation/edge.
	FighterAliasesTable = "fighter_alias"
	// FighterAliasesInverseTable is the table name for the FighterAlias entity.
	// It exists in this package in order to avoid circular dependency with the "fighteralias" package.
	FighterAliasesInverseTable = "fighter_alias"
	// FighterAliasesColumn is the table column denoting the fighter_aliases relation/edge.
	FighterAliasesColumn = "fighter_fighter_aliases"
	// FighterResultsTable is the table that holds the fighter_results relation/edge.
	FighterResultsTable = "fighter_results"
	// FighterResultsInverseTable is the table name for the FighterResults entity.
	// It exists in this package in order to avoid circular dependency with the "fighterresults" package.
	FighterResultsInverseTable = "fighter_results"
	// FighterResultsColumn is the table column denoting the fighter_results relation/edge.
	FighterResultsColumn = "fighter_id"
)

// Columns holds all SQL columns for fighter fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUfcFighterID,
	FieldMmaID,
	FieldFirstName,
	FieldLastName,
	FieldNickName,
	FieldFightinsiderID,
	FieldTapologyID,
}

var (
	// FightsPrimaryKey and FightsColumn2 are the table columns denoting the
	// primary key for the fights relation (M2M).
	FightsPrimaryKey = []string{"fight_id", "fighter_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// UfcFighterIDValidator is a validator for the "ufc_fighter_id" field. It is called by the builders before save.
	UfcFighterIDValidator func(string) error
)

// Order defines the ordering method for the Fighter queries.
type Order func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUfcFighterID orders the results by the ufc_fighter_id field.
func ByUfcFighterID(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldUfcFighterID, opts...).ToFunc()
}

// ByMmaID orders the results by the mma_id field.
func ByMmaID(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldMmaID, opts...).ToFunc()
}

// ByFirstName orders the results by the first_name field.
func ByFirstName(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldFirstName, opts...).ToFunc()
}

// ByLastName orders the results by the last_name field.
func ByLastName(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldLastName, opts...).ToFunc()
}

// ByNickName orders the results by the nick_name field.
func ByNickName(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldNickName, opts...).ToFunc()
}

// ByFightinsiderID orders the results by the fightinsider_id field.
func ByFightinsiderID(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldFightinsiderID, opts...).ToFunc()
}

// ByTapologyID orders the results by the tapology_id field.
func ByTapologyID(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldTapologyID, opts...).ToFunc()
}

// ByFightsCount orders the results by fights count.
func ByFightsCount(opts ...sql.OrderTermOption) Order {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFightsStep(), opts...)
	}
}

// ByFights orders the results by fights terms.
func ByFights(term sql.OrderTerm, terms ...sql.OrderTerm) Order {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFightsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFighterAliasesCount orders the results by fighter_aliases count.
func ByFighterAliasesCount(opts ...sql.OrderTermOption) Order {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFighterAliasesStep(), opts...)
	}
}

// ByFighterAliases orders the results by fighter_aliases terms.
func ByFighterAliases(term sql.OrderTerm, terms ...sql.OrderTerm) Order {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFighterAliasesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByFighterResultsCount orders the results by fighter_results count.
func ByFighterResultsCount(opts ...sql.OrderTermOption) Order {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFighterResultsStep(), opts...)
	}
}

// ByFighterResults orders the results by fighter_results terms.
func ByFighterResults(term sql.OrderTerm, terms ...sql.OrderTerm) Order {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFighterResultsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newFightsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FightsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, FightsTable, FightsPrimaryKey...),
	)
}
func newFighterAliasesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FighterAliasesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FighterAliasesTable, FighterAliasesColumn),
	)
}
func newFighterResultsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FighterResultsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, FighterResultsTable, FighterResultsColumn),
	)
}
