// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nherson/psc/api/ent/event"
	"github.com/nherson/psc/api/ent/fight"
	"github.com/nherson/psc/api/ent/fighter"
	"github.com/nherson/psc/api/ent/fighterresults"
	"github.com/nherson/psc/api/ent/predicate"
)

// FightQuery is the builder for querying Fight entities.
type FightQuery struct {
	config
	ctx                *QueryContext
	order              []fight.Order
	inters             []Interceptor
	predicates         []predicate.Fight
	withEvent          *EventQuery
	withFighters       *FighterQuery
	withFighterResults *FighterResultsQuery
	withFKs            bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FightQuery builder.
func (fq *FightQuery) Where(ps ...predicate.Fight) *FightQuery {
	fq.predicates = append(fq.predicates, ps...)
	return fq
}

// Limit the number of records to be returned by this query.
func (fq *FightQuery) Limit(limit int) *FightQuery {
	fq.ctx.Limit = &limit
	return fq
}

// Offset to start from.
func (fq *FightQuery) Offset(offset int) *FightQuery {
	fq.ctx.Offset = &offset
	return fq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fq *FightQuery) Unique(unique bool) *FightQuery {
	fq.ctx.Unique = &unique
	return fq
}

// Order specifies how the records should be ordered.
func (fq *FightQuery) Order(o ...fight.Order) *FightQuery {
	fq.order = append(fq.order, o...)
	return fq
}

// QueryEvent chains the current query on the "event" edge.
func (fq *FightQuery) QueryEvent() *EventQuery {
	query := (&EventClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fight.Table, fight.FieldID, selector),
			sqlgraph.To(event.Table, event.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, fight.EventTable, fight.EventColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFighters chains the current query on the "fighters" edge.
func (fq *FightQuery) QueryFighters() *FighterQuery {
	query := (&FighterClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fight.Table, fight.FieldID, selector),
			sqlgraph.To(fighter.Table, fighter.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, fight.FightersTable, fight.FightersPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFighterResults chains the current query on the "fighter_results" edge.
func (fq *FightQuery) QueryFighterResults() *FighterResultsQuery {
	query := (&FighterResultsClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fight.Table, fight.FieldID, selector),
			sqlgraph.To(fighterresults.Table, fighterresults.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, fight.FighterResultsTable, fight.FighterResultsColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Fight entity from the query.
// Returns a *NotFoundError when no Fight was found.
func (fq *FightQuery) First(ctx context.Context) (*Fight, error) {
	nodes, err := fq.Limit(1).All(setContextOp(ctx, fq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{fight.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fq *FightQuery) FirstX(ctx context.Context) *Fight {
	node, err := fq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Fight ID from the query.
// Returns a *NotFoundError when no Fight ID was found.
func (fq *FightQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fq.Limit(1).IDs(setContextOp(ctx, fq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{fight.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fq *FightQuery) FirstIDX(ctx context.Context) int {
	id, err := fq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Fight entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Fight entity is found.
// Returns a *NotFoundError when no Fight entities are found.
func (fq *FightQuery) Only(ctx context.Context) (*Fight, error) {
	nodes, err := fq.Limit(2).All(setContextOp(ctx, fq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{fight.Label}
	default:
		return nil, &NotSingularError{fight.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fq *FightQuery) OnlyX(ctx context.Context) *Fight {
	node, err := fq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Fight ID in the query.
// Returns a *NotSingularError when more than one Fight ID is found.
// Returns a *NotFoundError when no entities are found.
func (fq *FightQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fq.Limit(2).IDs(setContextOp(ctx, fq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{fight.Label}
	default:
		err = &NotSingularError{fight.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fq *FightQuery) OnlyIDX(ctx context.Context) int {
	id, err := fq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Fights.
func (fq *FightQuery) All(ctx context.Context) ([]*Fight, error) {
	ctx = setContextOp(ctx, fq.ctx, "All")
	if err := fq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Fight, *FightQuery]()
	return withInterceptors[[]*Fight](ctx, fq, qr, fq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fq *FightQuery) AllX(ctx context.Context) []*Fight {
	nodes, err := fq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Fight IDs.
func (fq *FightQuery) IDs(ctx context.Context) (ids []int, err error) {
	if fq.ctx.Unique == nil && fq.path != nil {
		fq.Unique(true)
	}
	ctx = setContextOp(ctx, fq.ctx, "IDs")
	if err = fq.Select(fight.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fq *FightQuery) IDsX(ctx context.Context) []int {
	ids, err := fq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fq *FightQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fq.ctx, "Count")
	if err := fq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fq, querierCount[*FightQuery](), fq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fq *FightQuery) CountX(ctx context.Context) int {
	count, err := fq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fq *FightQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fq.ctx, "Exist")
	switch _, err := fq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fq *FightQuery) ExistX(ctx context.Context) bool {
	exist, err := fq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FightQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fq *FightQuery) Clone() *FightQuery {
	if fq == nil {
		return nil
	}
	return &FightQuery{
		config:             fq.config,
		ctx:                fq.ctx.Clone(),
		order:              append([]fight.Order{}, fq.order...),
		inters:             append([]Interceptor{}, fq.inters...),
		predicates:         append([]predicate.Fight{}, fq.predicates...),
		withEvent:          fq.withEvent.Clone(),
		withFighters:       fq.withFighters.Clone(),
		withFighterResults: fq.withFighterResults.Clone(),
		// clone intermediate query.
		sql:  fq.sql.Clone(),
		path: fq.path,
	}
}

// WithEvent tells the query-builder to eager-load the nodes that are connected to
// the "event" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FightQuery) WithEvent(opts ...func(*EventQuery)) *FightQuery {
	query := (&EventClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withEvent = query
	return fq
}

// WithFighters tells the query-builder to eager-load the nodes that are connected to
// the "fighters" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FightQuery) WithFighters(opts ...func(*FighterQuery)) *FightQuery {
	query := (&FighterClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withFighters = query
	return fq
}

// WithFighterResults tells the query-builder to eager-load the nodes that are connected to
// the "fighter_results" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FightQuery) WithFighterResults(opts ...func(*FighterResultsQuery)) *FightQuery {
	query := (&FighterResultsClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withFighterResults = query
	return fq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Fight.Query().
//		GroupBy(fight.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fq *FightQuery) GroupBy(field string, fields ...string) *FightGroupBy {
	fq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FightGroupBy{build: fq}
	grbuild.flds = &fq.ctx.Fields
	grbuild.label = fight.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Fight.Query().
//		Select(fight.FieldCreatedAt).
//		Scan(ctx, &v)
func (fq *FightQuery) Select(fields ...string) *FightSelect {
	fq.ctx.Fields = append(fq.ctx.Fields, fields...)
	sbuild := &FightSelect{FightQuery: fq}
	sbuild.label = fight.Label
	sbuild.flds, sbuild.scan = &fq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FightSelect configured with the given aggregations.
func (fq *FightQuery) Aggregate(fns ...AggregateFunc) *FightSelect {
	return fq.Select().Aggregate(fns...)
}

func (fq *FightQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fq); err != nil {
				return err
			}
		}
	}
	for _, f := range fq.ctx.Fields {
		if !fight.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fq.path != nil {
		prev, err := fq.path(ctx)
		if err != nil {
			return err
		}
		fq.sql = prev
	}
	return nil
}

func (fq *FightQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Fight, error) {
	var (
		nodes       = []*Fight{}
		withFKs     = fq.withFKs
		_spec       = fq.querySpec()
		loadedTypes = [3]bool{
			fq.withEvent != nil,
			fq.withFighters != nil,
			fq.withFighterResults != nil,
		}
	)
	if fq.withEvent != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, fight.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Fight).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Fight{config: fq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := fq.withEvent; query != nil {
		if err := fq.loadEvent(ctx, query, nodes, nil,
			func(n *Fight, e *Event) { n.Edges.Event = e }); err != nil {
			return nil, err
		}
	}
	if query := fq.withFighters; query != nil {
		if err := fq.loadFighters(ctx, query, nodes,
			func(n *Fight) { n.Edges.Fighters = []*Fighter{} },
			func(n *Fight, e *Fighter) { n.Edges.Fighters = append(n.Edges.Fighters, e) }); err != nil {
			return nil, err
		}
	}
	if query := fq.withFighterResults; query != nil {
		if err := fq.loadFighterResults(ctx, query, nodes,
			func(n *Fight) { n.Edges.FighterResults = []*FighterResults{} },
			func(n *Fight, e *FighterResults) { n.Edges.FighterResults = append(n.Edges.FighterResults, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (fq *FightQuery) loadEvent(ctx context.Context, query *EventQuery, nodes []*Fight, init func(*Fight), assign func(*Fight, *Event)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Fight)
	for i := range nodes {
		if nodes[i].event_fights == nil {
			continue
		}
		fk := *nodes[i].event_fights
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(event.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "event_fights" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (fq *FightQuery) loadFighters(ctx context.Context, query *FighterQuery, nodes []*Fight, init func(*Fight), assign func(*Fight, *Fighter)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Fight)
	nids := make(map[int]map[*Fight]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(fight.FightersTable)
		s.Join(joinT).On(s.C(fighter.FieldID), joinT.C(fight.FightersPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(fight.FightersPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(fight.FightersPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Fight]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Fighter](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "fighters" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (fq *FightQuery) loadFighterResults(ctx context.Context, query *FighterResultsQuery, nodes []*Fight, init func(*Fight), assign func(*Fight, *FighterResults)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Fight)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.FighterResults(func(s *sql.Selector) {
		s.Where(sql.InValues(fight.FighterResultsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.FightID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "fight_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (fq *FightQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fq.querySpec()
	_spec.Node.Columns = fq.ctx.Fields
	if len(fq.ctx.Fields) > 0 {
		_spec.Unique = fq.ctx.Unique != nil && *fq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fq.driver, _spec)
}

func (fq *FightQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(fight.Table, fight.Columns, sqlgraph.NewFieldSpec(fight.FieldID, field.TypeInt))
	_spec.From = fq.sql
	if unique := fq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fq.path != nil {
		_spec.Unique = true
	}
	if fields := fq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fight.FieldID)
		for i := range fields {
			if fields[i] != fight.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fq *FightQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fq.driver.Dialect())
	t1 := builder.Table(fight.Table)
	columns := fq.ctx.Fields
	if len(columns) == 0 {
		columns = fight.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fq.sql != nil {
		selector = fq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fq.ctx.Unique != nil && *fq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fq.predicates {
		p(selector)
	}
	for _, p := range fq.order {
		p(selector)
	}
	if offset := fq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FightGroupBy is the group-by builder for Fight entities.
type FightGroupBy struct {
	selector
	build *FightQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fgb *FightGroupBy) Aggregate(fns ...AggregateFunc) *FightGroupBy {
	fgb.fns = append(fgb.fns, fns...)
	return fgb
}

// Scan applies the selector query and scans the result into the given value.
func (fgb *FightGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fgb.build.ctx, "GroupBy")
	if err := fgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FightQuery, *FightGroupBy](ctx, fgb.build, fgb, fgb.build.inters, v)
}

func (fgb *FightGroupBy) sqlScan(ctx context.Context, root *FightQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fgb.fns))
	for _, fn := range fgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fgb.flds)+len(fgb.fns))
		for _, f := range *fgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FightSelect is the builder for selecting fields of Fight entities.
type FightSelect struct {
	*FightQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fs *FightSelect) Aggregate(fns ...AggregateFunc) *FightSelect {
	fs.fns = append(fs.fns, fns...)
	return fs
}

// Scan applies the selector query and scans the result into the given value.
func (fs *FightSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fs.ctx, "Select")
	if err := fs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FightQuery, *FightSelect](ctx, fs.FightQuery, fs, fs.inters, v)
}

func (fs *FightSelect) sqlScan(ctx context.Context, root *FightQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fs.fns))
	for _, fn := range fs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
