// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nherson/psc/api/ent/fight"
	"github.com/nherson/psc/api/ent/fighter"
	"github.com/nherson/psc/api/ent/fighteralias"
	"github.com/nherson/psc/api/ent/fighterresults"
	"github.com/nherson/psc/api/ent/predicate"
)

// FighterQuery is the builder for querying Fighter entities.
type FighterQuery struct {
	config
	ctx                *QueryContext
	order              []fighter.Order
	inters             []Interceptor
	predicates         []predicate.Fighter
	withFights         *FightQuery
	withFighterAliases *FighterAliasQuery
	withFighterResults *FighterResultsQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FighterQuery builder.
func (fq *FighterQuery) Where(ps ...predicate.Fighter) *FighterQuery {
	fq.predicates = append(fq.predicates, ps...)
	return fq
}

// Limit the number of records to be returned by this query.
func (fq *FighterQuery) Limit(limit int) *FighterQuery {
	fq.ctx.Limit = &limit
	return fq
}

// Offset to start from.
func (fq *FighterQuery) Offset(offset int) *FighterQuery {
	fq.ctx.Offset = &offset
	return fq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fq *FighterQuery) Unique(unique bool) *FighterQuery {
	fq.ctx.Unique = &unique
	return fq
}

// Order specifies how the records should be ordered.
func (fq *FighterQuery) Order(o ...fighter.Order) *FighterQuery {
	fq.order = append(fq.order, o...)
	return fq
}

// QueryFights chains the current query on the "fights" edge.
func (fq *FighterQuery) QueryFights() *FightQuery {
	query := (&FightClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fighter.Table, fighter.FieldID, selector),
			sqlgraph.To(fight.Table, fight.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, fighter.FightsTable, fighter.FightsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFighterAliases chains the current query on the "fighter_aliases" edge.
func (fq *FighterQuery) QueryFighterAliases() *FighterAliasQuery {
	query := (&FighterAliasClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fighter.Table, fighter.FieldID, selector),
			sqlgraph.To(fighteralias.Table, fighteralias.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, fighter.FighterAliasesTable, fighter.FighterAliasesColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFighterResults chains the current query on the "fighter_results" edge.
func (fq *FighterQuery) QueryFighterResults() *FighterResultsQuery {
	query := (&FighterResultsClient{config: fq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fighter.Table, fighter.FieldID, selector),
			sqlgraph.To(fighterresults.Table, fighterresults.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, fighter.FighterResultsTable, fighter.FighterResultsColumn),
		)
		fromU = sqlgraph.SetNeighbors(fq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Fighter entity from the query.
// Returns a *NotFoundError when no Fighter was found.
func (fq *FighterQuery) First(ctx context.Context) (*Fighter, error) {
	nodes, err := fq.Limit(1).All(setContextOp(ctx, fq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{fighter.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fq *FighterQuery) FirstX(ctx context.Context) *Fighter {
	node, err := fq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Fighter ID from the query.
// Returns a *NotFoundError when no Fighter ID was found.
func (fq *FighterQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fq.Limit(1).IDs(setContextOp(ctx, fq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{fighter.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fq *FighterQuery) FirstIDX(ctx context.Context) int {
	id, err := fq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Fighter entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Fighter entity is found.
// Returns a *NotFoundError when no Fighter entities are found.
func (fq *FighterQuery) Only(ctx context.Context) (*Fighter, error) {
	nodes, err := fq.Limit(2).All(setContextOp(ctx, fq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{fighter.Label}
	default:
		return nil, &NotSingularError{fighter.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fq *FighterQuery) OnlyX(ctx context.Context) *Fighter {
	node, err := fq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Fighter ID in the query.
// Returns a *NotSingularError when more than one Fighter ID is found.
// Returns a *NotFoundError when no entities are found.
func (fq *FighterQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fq.Limit(2).IDs(setContextOp(ctx, fq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{fighter.Label}
	default:
		err = &NotSingularError{fighter.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fq *FighterQuery) OnlyIDX(ctx context.Context) int {
	id, err := fq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Fighters.
func (fq *FighterQuery) All(ctx context.Context) ([]*Fighter, error) {
	ctx = setContextOp(ctx, fq.ctx, "All")
	if err := fq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Fighter, *FighterQuery]()
	return withInterceptors[[]*Fighter](ctx, fq, qr, fq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fq *FighterQuery) AllX(ctx context.Context) []*Fighter {
	nodes, err := fq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Fighter IDs.
func (fq *FighterQuery) IDs(ctx context.Context) (ids []int, err error) {
	if fq.ctx.Unique == nil && fq.path != nil {
		fq.Unique(true)
	}
	ctx = setContextOp(ctx, fq.ctx, "IDs")
	if err = fq.Select(fighter.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fq *FighterQuery) IDsX(ctx context.Context) []int {
	ids, err := fq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fq *FighterQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fq.ctx, "Count")
	if err := fq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fq, querierCount[*FighterQuery](), fq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fq *FighterQuery) CountX(ctx context.Context) int {
	count, err := fq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fq *FighterQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fq.ctx, "Exist")
	switch _, err := fq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fq *FighterQuery) ExistX(ctx context.Context) bool {
	exist, err := fq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FighterQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fq *FighterQuery) Clone() *FighterQuery {
	if fq == nil {
		return nil
	}
	return &FighterQuery{
		config:             fq.config,
		ctx:                fq.ctx.Clone(),
		order:              append([]fighter.Order{}, fq.order...),
		inters:             append([]Interceptor{}, fq.inters...),
		predicates:         append([]predicate.Fighter{}, fq.predicates...),
		withFights:         fq.withFights.Clone(),
		withFighterAliases: fq.withFighterAliases.Clone(),
		withFighterResults: fq.withFighterResults.Clone(),
		// clone intermediate query.
		sql:  fq.sql.Clone(),
		path: fq.path,
	}
}

// WithFights tells the query-builder to eager-load the nodes that are connected to
// the "fights" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FighterQuery) WithFights(opts ...func(*FightQuery)) *FighterQuery {
	query := (&FightClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withFights = query
	return fq
}

// WithFighterAliases tells the query-builder to eager-load the nodes that are connected to
// the "fighter_aliases" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FighterQuery) WithFighterAliases(opts ...func(*FighterAliasQuery)) *FighterQuery {
	query := (&FighterAliasClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withFighterAliases = query
	return fq
}

// WithFighterResults tells the query-builder to eager-load the nodes that are connected to
// the "fighter_results" edge. The optional arguments are used to configure the query builder of the edge.
func (fq *FighterQuery) WithFighterResults(opts ...func(*FighterResultsQuery)) *FighterQuery {
	query := (&FighterResultsClient{config: fq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fq.withFighterResults = query
	return fq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UfcFighterID string `json:"ufc_fighter_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Fighter.Query().
//		GroupBy(fighter.FieldUfcFighterID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fq *FighterQuery) GroupBy(field string, fields ...string) *FighterGroupBy {
	fq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FighterGroupBy{build: fq}
	grbuild.flds = &fq.ctx.Fields
	grbuild.label = fighter.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UfcFighterID string `json:"ufc_fighter_id,omitempty"`
//	}
//
//	client.Fighter.Query().
//		Select(fighter.FieldUfcFighterID).
//		Scan(ctx, &v)
func (fq *FighterQuery) Select(fields ...string) *FighterSelect {
	fq.ctx.Fields = append(fq.ctx.Fields, fields...)
	sbuild := &FighterSelect{FighterQuery: fq}
	sbuild.label = fighter.Label
	sbuild.flds, sbuild.scan = &fq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FighterSelect configured with the given aggregations.
func (fq *FighterQuery) Aggregate(fns ...AggregateFunc) *FighterSelect {
	return fq.Select().Aggregate(fns...)
}

func (fq *FighterQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fq); err != nil {
				return err
			}
		}
	}
	for _, f := range fq.ctx.Fields {
		if !fighter.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fq.path != nil {
		prev, err := fq.path(ctx)
		if err != nil {
			return err
		}
		fq.sql = prev
	}
	return nil
}

func (fq *FighterQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Fighter, error) {
	var (
		nodes       = []*Fighter{}
		_spec       = fq.querySpec()
		loadedTypes = [3]bool{
			fq.withFights != nil,
			fq.withFighterAliases != nil,
			fq.withFighterResults != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Fighter).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Fighter{config: fq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := fq.withFights; query != nil {
		if err := fq.loadFights(ctx, query, nodes,
			func(n *Fighter) { n.Edges.Fights = []*Fight{} },
			func(n *Fighter, e *Fight) { n.Edges.Fights = append(n.Edges.Fights, e) }); err != nil {
			return nil, err
		}
	}
	if query := fq.withFighterAliases; query != nil {
		if err := fq.loadFighterAliases(ctx, query, nodes,
			func(n *Fighter) { n.Edges.FighterAliases = []*FighterAlias{} },
			func(n *Fighter, e *FighterAlias) { n.Edges.FighterAliases = append(n.Edges.FighterAliases, e) }); err != nil {
			return nil, err
		}
	}
	if query := fq.withFighterResults; query != nil {
		if err := fq.loadFighterResults(ctx, query, nodes,
			func(n *Fighter) { n.Edges.FighterResults = []*FighterResults{} },
			func(n *Fighter, e *FighterResults) { n.Edges.FighterResults = append(n.Edges.FighterResults, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (fq *FighterQuery) loadFights(ctx context.Context, query *FightQuery, nodes []*Fighter, init func(*Fighter), assign func(*Fighter, *Fight)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*Fighter)
	nids := make(map[int]map[*Fighter]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(fighter.FightsTable)
		s.Join(joinT).On(s.C(fight.FieldID), joinT.C(fighter.FightsPrimaryKey[0]))
		s.Where(sql.InValues(joinT.C(fighter.FightsPrimaryKey[1]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(fighter.FightsPrimaryKey[1]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Fighter]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Fight](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "fights" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (fq *FighterQuery) loadFighterAliases(ctx context.Context, query *FighterAliasQuery, nodes []*Fighter, init func(*Fighter), assign func(*Fighter, *FighterAlias)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Fighter)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.FighterAlias(func(s *sql.Selector) {
		s.Where(sql.InValues(fighter.FighterAliasesColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.fighter_fighter_aliases
		if fk == nil {
			return fmt.Errorf(`foreign-key "fighter_fighter_aliases" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "fighter_fighter_aliases" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (fq *FighterQuery) loadFighterResults(ctx context.Context, query *FighterResultsQuery, nodes []*Fighter, init func(*Fighter), assign func(*Fighter, *FighterResults)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Fighter)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.FighterResults(func(s *sql.Selector) {
		s.Where(sql.InValues(fighter.FighterResultsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.FighterID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "fighter_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (fq *FighterQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fq.querySpec()
	_spec.Node.Columns = fq.ctx.Fields
	if len(fq.ctx.Fields) > 0 {
		_spec.Unique = fq.ctx.Unique != nil && *fq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fq.driver, _spec)
}

func (fq *FighterQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(fighter.Table, fighter.Columns, sqlgraph.NewFieldSpec(fighter.FieldID, field.TypeInt))
	_spec.From = fq.sql
	if unique := fq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fq.path != nil {
		_spec.Unique = true
	}
	if fields := fq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fighter.FieldID)
		for i := range fields {
			if fields[i] != fighter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fq *FighterQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fq.driver.Dialect())
	t1 := builder.Table(fighter.Table)
	columns := fq.ctx.Fields
	if len(columns) == 0 {
		columns = fighter.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fq.sql != nil {
		selector = fq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fq.ctx.Unique != nil && *fq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fq.predicates {
		p(selector)
	}
	for _, p := range fq.order {
		p(selector)
	}
	if offset := fq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FighterGroupBy is the group-by builder for Fighter entities.
type FighterGroupBy struct {
	selector
	build *FighterQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fgb *FighterGroupBy) Aggregate(fns ...AggregateFunc) *FighterGroupBy {
	fgb.fns = append(fgb.fns, fns...)
	return fgb
}

// Scan applies the selector query and scans the result into the given value.
func (fgb *FighterGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fgb.build.ctx, "GroupBy")
	if err := fgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FighterQuery, *FighterGroupBy](ctx, fgb.build, fgb, fgb.build.inters, v)
}

func (fgb *FighterGroupBy) sqlScan(ctx context.Context, root *FighterQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(fgb.fns))
	for _, fn := range fgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*fgb.flds)+len(fgb.fns))
		for _, f := range *fgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*fgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FighterSelect is the builder for selecting fields of Fighter entities.
type FighterSelect struct {
	*FighterQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fs *FighterSelect) Aggregate(fns ...AggregateFunc) *FighterSelect {
	fs.fns = append(fs.fns, fns...)
	return fs
}

// Scan applies the selector query and scans the result into the given value.
func (fs *FighterSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fs.ctx, "Select")
	if err := fs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FighterQuery, *FighterSelect](ctx, fs.FighterQuery, fs, fs.inters, v)
}

func (fs *FighterSelect) sqlScan(ctx context.Context, root *FighterQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fs.fns))
	for _, fn := range fs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
