// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/nherson/psc/api/ent/predicate"
	"github.com/nherson/psc/api/ent/upcomingevent"
)

// UpcomingEventQuery is the builder for querying UpcomingEvent entities.
type UpcomingEventQuery struct {
	config
	ctx        *QueryContext
	order      []upcomingevent.Order
	inters     []Interceptor
	predicates []predicate.UpcomingEvent
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UpcomingEventQuery builder.
func (ueq *UpcomingEventQuery) Where(ps ...predicate.UpcomingEvent) *UpcomingEventQuery {
	ueq.predicates = append(ueq.predicates, ps...)
	return ueq
}

// Limit the number of records to be returned by this query.
func (ueq *UpcomingEventQuery) Limit(limit int) *UpcomingEventQuery {
	ueq.ctx.Limit = &limit
	return ueq
}

// Offset to start from.
func (ueq *UpcomingEventQuery) Offset(offset int) *UpcomingEventQuery {
	ueq.ctx.Offset = &offset
	return ueq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ueq *UpcomingEventQuery) Unique(unique bool) *UpcomingEventQuery {
	ueq.ctx.Unique = &unique
	return ueq
}

// Order specifies how the records should be ordered.
func (ueq *UpcomingEventQuery) Order(o ...upcomingevent.Order) *UpcomingEventQuery {
	ueq.order = append(ueq.order, o...)
	return ueq
}

// First returns the first UpcomingEvent entity from the query.
// Returns a *NotFoundError when no UpcomingEvent was found.
func (ueq *UpcomingEventQuery) First(ctx context.Context) (*UpcomingEvent, error) {
	nodes, err := ueq.Limit(1).All(setContextOp(ctx, ueq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{upcomingevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ueq *UpcomingEventQuery) FirstX(ctx context.Context) *UpcomingEvent {
	node, err := ueq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UpcomingEvent ID from the query.
// Returns a *NotFoundError when no UpcomingEvent ID was found.
func (ueq *UpcomingEventQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ueq.Limit(1).IDs(setContextOp(ctx, ueq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{upcomingevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ueq *UpcomingEventQuery) FirstIDX(ctx context.Context) int {
	id, err := ueq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UpcomingEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UpcomingEvent entity is found.
// Returns a *NotFoundError when no UpcomingEvent entities are found.
func (ueq *UpcomingEventQuery) Only(ctx context.Context) (*UpcomingEvent, error) {
	nodes, err := ueq.Limit(2).All(setContextOp(ctx, ueq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{upcomingevent.Label}
	default:
		return nil, &NotSingularError{upcomingevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ueq *UpcomingEventQuery) OnlyX(ctx context.Context) *UpcomingEvent {
	node, err := ueq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UpcomingEvent ID in the query.
// Returns a *NotSingularError when more than one UpcomingEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (ueq *UpcomingEventQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ueq.Limit(2).IDs(setContextOp(ctx, ueq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{upcomingevent.Label}
	default:
		err = &NotSingularError{upcomingevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ueq *UpcomingEventQuery) OnlyIDX(ctx context.Context) int {
	id, err := ueq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UpcomingEvents.
func (ueq *UpcomingEventQuery) All(ctx context.Context) ([]*UpcomingEvent, error) {
	ctx = setContextOp(ctx, ueq.ctx, "All")
	if err := ueq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UpcomingEvent, *UpcomingEventQuery]()
	return withInterceptors[[]*UpcomingEvent](ctx, ueq, qr, ueq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ueq *UpcomingEventQuery) AllX(ctx context.Context) []*UpcomingEvent {
	nodes, err := ueq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UpcomingEvent IDs.
func (ueq *UpcomingEventQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ueq.ctx.Unique == nil && ueq.path != nil {
		ueq.Unique(true)
	}
	ctx = setContextOp(ctx, ueq.ctx, "IDs")
	if err = ueq.Select(upcomingevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ueq *UpcomingEventQuery) IDsX(ctx context.Context) []int {
	ids, err := ueq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ueq *UpcomingEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ueq.ctx, "Count")
	if err := ueq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ueq, querierCount[*UpcomingEventQuery](), ueq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ueq *UpcomingEventQuery) CountX(ctx context.Context) int {
	count, err := ueq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ueq *UpcomingEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ueq.ctx, "Exist")
	switch _, err := ueq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ueq *UpcomingEventQuery) ExistX(ctx context.Context) bool {
	exist, err := ueq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UpcomingEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ueq *UpcomingEventQuery) Clone() *UpcomingEventQuery {
	if ueq == nil {
		return nil
	}
	return &UpcomingEventQuery{
		config:     ueq.config,
		ctx:        ueq.ctx.Clone(),
		order:      append([]upcomingevent.Order{}, ueq.order...),
		inters:     append([]Interceptor{}, ueq.inters...),
		predicates: append([]predicate.UpcomingEvent{}, ueq.predicates...),
		// clone intermediate query.
		sql:  ueq.sql.Clone(),
		path: ueq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UpcomingEvent.Query().
//		GroupBy(upcomingevent.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ueq *UpcomingEventQuery) GroupBy(field string, fields ...string) *UpcomingEventGroupBy {
	ueq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UpcomingEventGroupBy{build: ueq}
	grbuild.flds = &ueq.ctx.Fields
	grbuild.label = upcomingevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.UpcomingEvent.Query().
//		Select(upcomingevent.FieldCreatedAt).
//		Scan(ctx, &v)
func (ueq *UpcomingEventQuery) Select(fields ...string) *UpcomingEventSelect {
	ueq.ctx.Fields = append(ueq.ctx.Fields, fields...)
	sbuild := &UpcomingEventSelect{UpcomingEventQuery: ueq}
	sbuild.label = upcomingevent.Label
	sbuild.flds, sbuild.scan = &ueq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UpcomingEventSelect configured with the given aggregations.
func (ueq *UpcomingEventQuery) Aggregate(fns ...AggregateFunc) *UpcomingEventSelect {
	return ueq.Select().Aggregate(fns...)
}

func (ueq *UpcomingEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ueq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ueq); err != nil {
				return err
			}
		}
	}
	for _, f := range ueq.ctx.Fields {
		if !upcomingevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ueq.path != nil {
		prev, err := ueq.path(ctx)
		if err != nil {
			return err
		}
		ueq.sql = prev
	}
	return nil
}

func (ueq *UpcomingEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UpcomingEvent, error) {
	var (
		nodes = []*UpcomingEvent{}
		_spec = ueq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UpcomingEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UpcomingEvent{config: ueq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ueq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ueq *UpcomingEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ueq.querySpec()
	_spec.Node.Columns = ueq.ctx.Fields
	if len(ueq.ctx.Fields) > 0 {
		_spec.Unique = ueq.ctx.Unique != nil && *ueq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ueq.driver, _spec)
}

func (ueq *UpcomingEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(upcomingevent.Table, upcomingevent.Columns, sqlgraph.NewFieldSpec(upcomingevent.FieldID, field.TypeInt))
	_spec.From = ueq.sql
	if unique := ueq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ueq.path != nil {
		_spec.Unique = true
	}
	if fields := ueq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upcomingevent.FieldID)
		for i := range fields {
			if fields[i] != upcomingevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ueq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ueq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ueq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ueq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ueq *UpcomingEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ueq.driver.Dialect())
	t1 := builder.Table(upcomingevent.Table)
	columns := ueq.ctx.Fields
	if len(columns) == 0 {
		columns = upcomingevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ueq.sql != nil {
		selector = ueq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ueq.ctx.Unique != nil && *ueq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ueq.predicates {
		p(selector)
	}
	for _, p := range ueq.order {
		p(selector)
	}
	if offset := ueq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ueq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UpcomingEventGroupBy is the group-by builder for UpcomingEvent entities.
type UpcomingEventGroupBy struct {
	selector
	build *UpcomingEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uegb *UpcomingEventGroupBy) Aggregate(fns ...AggregateFunc) *UpcomingEventGroupBy {
	uegb.fns = append(uegb.fns, fns...)
	return uegb
}

// Scan applies the selector query and scans the result into the given value.
func (uegb *UpcomingEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uegb.build.ctx, "GroupBy")
	if err := uegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpcomingEventQuery, *UpcomingEventGroupBy](ctx, uegb.build, uegb, uegb.build.inters, v)
}

func (uegb *UpcomingEventGroupBy) sqlScan(ctx context.Context, root *UpcomingEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uegb.fns))
	for _, fn := range uegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uegb.flds)+len(uegb.fns))
		for _, f := range *uegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UpcomingEventSelect is the builder for selecting fields of UpcomingEvent entities.
type UpcomingEventSelect struct {
	*UpcomingEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ues *UpcomingEventSelect) Aggregate(fns ...AggregateFunc) *UpcomingEventSelect {
	ues.fns = append(ues.fns, fns...)
	return ues
}

// Scan applies the selector query and scans the result into the given value.
func (ues *UpcomingEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ues.ctx, "Select")
	if err := ues.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UpcomingEventQuery, *UpcomingEventSelect](ctx, ues.UpcomingEventQuery, ues, ues.inters, v)
}

func (ues *UpcomingEventSelect) sqlScan(ctx context.Context, root *UpcomingEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ues.fns))
	for _, fn := range ues.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ues.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ues.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
