-- Modify "events" table
ALTER TABLE "events" ADD COLUMN "ufc_event_id" character varying NOT NULL, ADD COLUMN "name" character varying NOT NULL;
-- Create index "events_ufc_event_id_key" to table: "events"
CREATE UNIQUE INDEX "events_ufc_event_id_key" ON "events" ("ufc_event_id");
-- Modify "fights" table
ALTER TABLE "fights" ADD COLUMN "ufc_fight_id" character varying NOT NULL, ADD COLUMN "card_order" bigint NOT NULL, ADD COLUMN "card_segment" character varying NOT NULL, ADD COLUMN "result_method" character varying NOT NULL, ADD COLUMN "result_ending_round" bigint NOT NULL, ADD COLUMN "result_ending_time_seconds" bigint NOT NULL, ADD COLUMN "event_fights" bigint NULL, ADD CONSTRAINT "fights_events_fights" FOREIGN KEY ("event_fights") REFERENCES "events" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Create index "fights_ufc_fight_id_key" to table: "fights"
CREATE UNIQUE INDEX "fights_ufc_fight_id_key" ON "fights" ("ufc_fight_id");
-- Create "fighter_results" table
CREATE TABLE "fighter_results" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "significant_strikes_landed" bigint NOT NULL, "takedowns" bigint NOT NULL, "knockdowns" bigint NOT NULL, "control_time_seconds" bigint NOT NULL, "win_by_stoppage" boolean NOT NULL, "loss_by_stoppage" boolean NOT NULL, "missed_weight" boolean NOT NULL, "fighter_id" bigint NOT NULL, "fight_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "fighter_results_fighters_fighter" FOREIGN KEY ("fighter_id") REFERENCES "fighters" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "fighter_results_fights_fight" FOREIGN KEY ("fight_id") REFERENCES "fights" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "fighterresults_fight_id_fighter_id" to table: "fighter_results"
CREATE UNIQUE INDEX "fighterresults_fight_id_fighter_id" ON "fighter_results" ("fight_id", "fighter_id");
-- Modify "fighter_alias" table
ALTER TABLE "fighter_alias" ADD COLUMN "alias" character varying NOT NULL, ADD COLUMN "fighter_fighter_aliases" bigint NULL, ADD CONSTRAINT "fighter_alias_fighters_fighter_aliases" FOREIGN KEY ("fighter_fighter_aliases") REFERENCES "fighters" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
