-- Modify "upcoming_events" table
ALTER TABLE "upcoming_events" ADD COLUMN "tapology_id" character varying NOT NULL, ADD COLUMN "name" character varying NOT NULL, ADD COLUMN "date" timestamptz NOT NULL;
-- Modify "upcoming_fights" table
ALTER TABLE "upcoming_fights" ADD COLUMN "card_order" bigint NOT NULL, ADD COLUMN "upcoming_event_upcoming_fights" bigint NULL, ADD CONSTRAINT "upcoming_fights_upcoming_events_upcoming_fights" FOREIGN KEY ("upcoming_event_upcoming_fights") REFERENCES "upcoming_events" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Create "upcoming_fighter_odds" table
CREATE TABLE "upcoming_fighter_odds" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "best_odds" bigint NULL, "corner" character varying NOT NULL DEFAULT 'red', "fighter_id" bigint NOT NULL, "upcoming_fight_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "upcoming_fighter_odds_fighters_fighter" FOREIGN KEY ("fighter_id") REFERENCES "fighters" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "upcoming_fighter_odds_upcoming_fights_upcoming_fight" FOREIGN KEY ("upcoming_fight_id") REFERENCES "upcoming_fights" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "upcomingfighterodds_upcoming_fight_id_fighter_id" to table: "upcoming_fighter_odds"
CREATE UNIQUE INDEX "upcomingfighterodds_upcoming_fight_id_fighter_id" ON "upcoming_fighter_odds" ("upcoming_fight_id", "fighter_id");
