// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Fight is the predicate function for fight builders.
type Fight func(*sql.Selector)

// Fighter is the predicate function for fighter builders.
type Fighter func(*sql.Selector)

// FighterAlias is the predicate function for fighteralias builders.
type FighterAlias func(*sql.Selector)

// FighterResults is the predicate function for fighterresults builders.
type FighterResults func(*sql.Selector)

// UpcomingEvent is the predicate function for upcomingevent builders.
type UpcomingEvent func(*sql.Selector)

// UpcomingFight is the predicate function for upcomingfight builders.
type UpcomingFight func(*sql.Selector)

// UpcomingFighterOdds is the predicate function for upcomingfighterodds builders.
type UpcomingFighterOdds func(*sql.Selector)
