// Code generated by ent, DO NOT EDIT.

package upcomingevent

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the upcomingevent type in the database.
	Label = "upcoming_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the upcomingevent in the database.
	Table = "upcoming_events"
)

// Columns holds all SQL columns for upcomingevent fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Order defines the ordering method for the UpcomingEvent queries.
type Order func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) Order {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}
